services:
  spring2-build-linux:
    build:
      context: ../../../
      dockerfile: scripts/docker/linux/Dockerfile
    image: spring2-linux:latest
    container_name: spring2-dev
    volumes:
      - ../../../:/spring2
    working_dir: /spring2
    command: /bin/bash
    stdin_open: true
    tty: true
