services:
  spring2-build-windows:
    build:
      context: ../../../
      dockerfile: dev/docker/windows/Dockerfile
    image: spring2-windows:latest
    container_name: spring2-windows-dev
    volumes:
      - ../../../:C:\spring2
    working_dir: C:\spring2
    stdin_open: true
    tty: true
