services:
  spring2-build-macos:
    build:
      context: ../../../
      dockerfile: dev/docker/macos/Dockerfile
    image: spring2-macos:latest
    container_name: spring2-macos-dev
    volumes:
      - ../../../:/spring2
    working_dir: /spring2
    command: /bin/bash
    stdin_open: true
    tty: true
