#!/usr/bin/env python3
"""Compress a file and emit it as a C++ byte-array source file."""
import sys
import zlib

if len(sys.argv) != 3:
    print(f"Usage: {sys.argv[0]} <input> <output.cpp>", file=sys.stderr)
    sys.exit(1)

input_path, output_path = sys.argv[1], sys.argv[2]

with open(input_path, "rb") as f:
    raw = f.read()

compressed = zlib.compress(raw, level=9)

hex_bytes = ", ".join(f"0x{b:02x}" for b in compressed)

with open(output_path, "w") as f:
    f.write(
        f"""\
// Auto-generated by cmake/embed_reference.py — do not edit.
#include <cstddef>
namespace spring {{
extern const unsigned char kEmbeddedReference[];
extern const std::size_t kEmbeddedReferenceCompressedSize;
extern const std::size_t kEmbeddedReferenceUncompressedSize;
const unsigned char kEmbeddedReference[] = {{{hex_bytes}}};
const std::size_t kEmbeddedReferenceCompressedSize = {len(compressed)};
const std::size_t kEmbeddedReferenceUncompressedSize = {len(raw)};
}}
"""
    )
